---
SITE_NAME: "Demo-us1"
ORG_ID: "7783b965-7460-4a37-b6e7-5f6c575ba5cc"
TIME_ZONE: "America/Los_Angeles"
COUNTRY_CODE: "US"
ADDRESS: "1601 S. Deanza Blvd., Cupertino, CA, 95014"
API_TOKEN: "Basic c3VubnlhbnIzMUBnbWFpbC5jb206UGVuaG9yc2UjMw=="

